# Generated by Django 4.1.2 on 2022-10-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contact"),
    ]

    operations = [
        migrations.RemoveField(model_name="contact", name="surname",),
    ]
