# Generated by Django 4.1.2 on 2022-10-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="intro",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
